# Generated by Django 6.1 on 2026-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lsa', 'start_time', 'end_time'], name='booking_lsa_time_idx'),
        ),
    ]
